global using System.Diagnostics;
global using System.Net;
global using System.Net.Http.Headers;
global using System.Net.NetworkInformation;
global using System.Net.Sockets;
global using System.Runtime.InteropServices;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Threading.Channels;
